"""Criação inicial das tabelas

Revision ID: db63a2431d0c
Revises: 
Create Date: 2025-09-26 18:38:20.103298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db63a2431d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cnpj')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=False)
    op.create_table('licitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_licitacao', sa.String(), nullable=False),
    sa.Column('objeto', sa.String(), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_id'), 'licitacoes', ['id'], unique=False)
    op.create_index(op.f('ix_licitacoes_numero_licitacao'), 'licitacoes', ['numero_licitacao'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(), nullable=False),
    sa.Column('valor_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('licitacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_cnpj'], ['fornecedores.cnpj'], ),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_index(op.f('ix_contratos_numero_contrato'), 'contratos', ['numero_contrato'], unique=True)
    op.create_table('licitacao_fornecedor',
    sa.Column('licitacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_cnpj'], ['fornecedores.cnpj'], ),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('licitacao_id', 'fornecedor_cnpj')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licitacao_fornecedor')
    op.drop_index(op.f('ix_contratos_numero_contrato'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_licitacoes_numero_licitacao'), table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_id'), table_name='licitacoes')
    op.drop_table('licitacoes')
    op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
